SELECT TOP 25 PERCENT
	 Abstract
	,AcidVolume_BBL
	,AlternativeWellName
	,API_UWI
	,API_UWI_Unformatted
	,API_UWI_12
	,API_UWI_12_Unformatted
	,API_UWI_14
	,API_UWI_14_Unformatted
	,AverageStageSpacing_FT
	,AvgBreakdownPressure_PSI
	,AvgClusterSpacing_FT
	,AvgClusterSpacingPerStage_FT
	,AvgFluidPerCluster_BBL
	,AvgFluidPerShot_BBL
	,AvgFluidPerStage_BBL
	,AvgFracGradient_PSIPerFT
	,AvgISIP_PSI
	,AvgMillTime_Min
	,AvgPortSleeveOpeningPressure_PSI
	,AvgProppantPerCluster_LBS
	,AvgProppantPerShot_LBS
	,AvgProppantPerStage_LBS
	,AvgShotsPerCluster
	,AvgShotsPerFT
	,AvgTreatmentPressure_PSI
	,AvgTreatmentRate_BBLPerMin
	,Biocide_LBS
	,Block
	,Bottom_Hole_Temp_DEGF
	,BottomHoleAge
	,BottomHoleFormationName
	,BottomHoleLithology
	,Breaker_LBS
	,Buffer_LBS
	,CasingPressure_PSI
	,ChokeSize_64IN
	,ClayControl_LBS
	,ClustersPer1000FT
	,ClustersPerStage
	,CompletionDate
	,CompletionDesign
	,CompletionID
	,CompletionNumber
	,CompletionTime_DAYS
	,Contract
	,CoordinateQuality
	,CoordinateSource
	,Country
	,County
	,CrossLinker_LBS
	,CumGas_MCF
	,CumGas_MCFPer1000FT
	,CumOil_BBL
	,CumOil_BBLPer1000FT
	,CumProd_BOE
	,CumProd_BOEPer1000FT
	,CumProd_MCFE
	,CumProd_MCFEPer1000FT
	,CumulativeSOR
	,CumWater_BBL
	,DeletedDate
	,DevelopmentFlag
	,DiscoverMagnitudeComments
	,DiscoveryType
	,District
	,Diverter_LBS
	,DrillingEndDate
	,DrillingTDDate
	,DrillingTDDateQualifier
	,ElevationGL_FT
	,ElevationKB_FT
	,EndDateQualifier
	,Energizer_LBS
	,ENVBasin
	,ENVCompInsertedDate
	,ENVElevationGL_FT
	,ENVElevationGLSource
	,ENVElevationKB_FT
	,ENVElevationKBSource
	,ENVFluidType
	,ENVFracJobType
	,ENVInterval
	,ENVIntervalSource
	,Environment
	,ENVOperator
	,ENVPeerGroup
	,ENVPlay
	,ENVProducingMethod
	,ENVProdWellType
	,ENVProppantBrand
	,ENVProppantType
	,ENVRegion
	,ENVStockExchange
	,ENVSubPlay
	,ENVTicker
	,ENVWellboreType
	,ENVWellGrouping
	,ENVWellServiceProvider
	,ENVWellStatus
	,ENVWellType
	,ExplorationFlag
	,Field
	,First3MonthFlaredGas_MCF
	,First3MonthGas_MCF
	,First3MonthGas_MCFPer1000FT
	,First3MonthOil_BBL
	,First3MonthOil_BBLPer1000FT
	,First3MonthProd_BOE
	,First3MonthProd_BOEPer1000FT
	,First3MonthProd_MCFE
	,First3MonthProd_MCFEPer1000FT
	,First3MonthWater_BBL
	,First6MonthFlaredGas_MCF
	,First6MonthGas_MCF
	,First6MonthGas_MCFPer1000FT
	,First6MonthOil_BBL
	,First6MonthOil_BBLPer1000FT
	,First6MonthProd_BOE
	,First6MonthProd_BOEPer1000FT
	,First6MonthProd_MCFE
	,First6MonthProd_MCFEPer1000FT
	,First6MonthWater_BBL
	,First9MonthFlaredGas_MCF
	,First9MonthGas_MCF
	,First9MonthGas_MCFPer1000FT
	,First9MonthOil_BBL
	,First9MonthOil_BBLPer1000FT
	,First9MonthProd_BOE
	,First9MonthProd_BOEPer1000FT
	,First9MonthProd_MCFE
	,First9MonthProd_MCFEPer1000FT
	,First9MonthWater_BBL
	,First12MonthFlaredGas_MCF
	,First12MonthGas_MCF
	,First12MonthGas_MCFPer1000FT
	,First12MonthOil_BBL
	,First12MonthOil_BBLPer1000FT
	,First12MonthProd_BOE
	,First12MonthProd_BOEPer1000FT
	,First12MonthProd_MCFE
	,First12MonthProd_MCFEPer1000FT
	,First12MonthWater_BBL
	,First36MonthGas_MCF
	,First36MonthGas_MCFPer1000FT
	,First36MonthOil_BBL
	,First36MonthOil_BBLPer1000FT
	,First36MonthProd_BOE
	,First36MonthProd_BOEPer1000FT
	,First36MonthProd_MCFE
	,First36MonthProd_MCFEPer1000FT
	,First36MonthWater_BBL
	,First36MonthWaterProductionBBLPer1000Ft
	,FirstDay
	,FirstProdDate
	,FirstProdMonth
	,FirstProdQuarter
	,FirstProdYear
	,FlaredGasRatio
	,FlowingTubingPressure_PSI
	,FluidIntensity_BBLPerFT
	,Formation
	,FracRigOnsiteDate
	,FracRigReleaseDate
	,FracStages
	,FrictionReducer_LBS
	,GasGravity_SG
	,GasTestRate_MCFPerDAY
	,GasTestRate_MCFPerDAYPer1000FT
	,GellingAgent_LBS
	,GeneralComments
	,GeomBHL_Point			= try_convert(varbinary(max), GeomBHL_Point)
	,GeomSHL_Point			= try_convert(varbinary(max), GeomSHL_Point)
	,GOR_ScfPerBbl
	,GovernmentWellId
	,InitialOperator
	,IronControl_LBS
	,Last3MonthISOR
	,Last12MonthGasProduction_MCF
	,Last12MonthOilProduction_BBL
	,Last12MonthProduction_BOE
	,Last12MonthWaterProduction_BBL
	,LastMonthFlaredGas_MCF
	,LastMonthGasProduction_MCF
	,LastMonthLiquidsProduction_BBL
	,LastMonthWaterProduction_BBL
	,LastProducingMonth
	,LateralLength_FT
	,LateralLine						=  try_convert(VARBINARY(max), LateralLine)
	,Latitude
	,Latitude_BH
	,Lease
	,LeaseName
	,Longitude
	,Longitude_BH
	,LowerPerf_FT
	,MD_FT
	,MonthsToPeakProduction
	,NumberOfStrings
	,ObjectiveAge
	,ObjectiveLithology
	,OffConfidentialDate
	,OilGravity_API
	,OilProdPriorTest_BBL
	,OilTestMethodName
	,OilTestRate_BBLPerDAY
	,OilTestRate_BBLPerDAYPer1000FT
	,OnConfidential
	,OnOffshore
	,PeakFlaredGas_MCF
	,PeakGas_MCF
	,PeakGas_MCFPer1000FT
	,PeakOil_BBL
	,PeakOil_BBLPer1000FT
	,PeakProd_BOE
	,PeakProd_BOEPer1000FT
	,PeakProd_MCFE
	,PeakProd_MCFEPer1000FT
	,PeakProductionDate
	,PeakWater_BBL
	,PerfInterval_FT
	,PermitApprovedDate
	,PermitSubmittedDate
	,PermitToSpud_DAYS
	,Platform
	,PlugbackMeasuredDepth_FT
	,PlugbackTrueVerticalDepth_FT
	,PlugDate
	,Proppant_LBS
	,ProppantIntensity_LBSPerFT
	,ProppantLoading_LBSPerGAL
	,Range
	,RawOperator
	,RawVintage
	,ResourceMagnitude
	,ResourceMagnitudeReviewDate
	,ResourceSourceQualifier
	,ResourceVolumeGasBcf
	,ResourceVolumeLiquidsMMb
	,RigReleaseDate
	,ScaleInhibitor_LBS
	,Section
	,Section_Township_Range
	,ShotsPer1000FT
	,ShotsPerStage
	,ShutInPressure_PSI
	,SoakTime_DAYS
	,SpudDate
	,SpudDateQualifier
	,SpudDateSource
	,SpudToCompletion_DAYS
	,SpudToRigRelease_DAYS
	,SpudToSales_DAYS
	,StateFileNumber
	,StateProvince
	,StateWellType
	,StimulatedStages
	,SurfaceLatLongSource
	,Surfactant_LBS
	,TestComments
	,TestDate
	,TestRate_BOEPerDAY
	,TestRate_BOEPerDAYPer1000FT
	,TestRate_MCFEPerDAY
	,TestRate_MCFEPerDAYPer1000FT
	,TestWHLiquids_PCT
	,TotalClusters
	,TotalFluidPumped_BBL
	,TotalProducingMonths
	,TotalShots
	,TotalWaterPumped_GAL
	,Township
	,Trajectory
	,TVD_FT
	,UnconventionalFlag
	,UnconventionalType
	,Unit_Name
	,UpdatedDate
	,UpperPerf_FT
	,Vintage
	,WaterDepth
	,WaterIntensity_GALPerFT
	,WaterSaturation_PCT
	,WaterTestRate_BBLPerDAY
	,WaterTestRate_BBLPerDAYPer1000FT
	,WellboreID
	,WellID
	,WellName
	,WellNumber
	,WellPadDirection
	,WellPadID
	,WellSymbols
	,WHLiquids_PCT
	,ETL_Load_date
FROM
	Stage_Persistent.Enverus_Foundations_Wells