USE [EDW]
GO

/****** Object:  View [Master_Etl].[Dimensional_Well_Header]    Script Date: 10/6/2024 12:16:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO














ALTER VIEW [Master_Etl].[Dimensional_Well_Header]
AS
SELECT
    mwh.Master_Hub_Well_Header_UID
   ,coalesce(NULL, swhwv.API_County_Name, swhsf.API_County_Name, swha.API_County_Name, swhe.API_County_Name, swhm.API_County_Name, swhp.API_County_Name)                                                                                                                                                                                                                                                                                                                   AS API_County_Name
---,COALESCE(NULL, swhwv.API_Number, swhsf.API_Number, swha.API_Number, swhe.API_Number, swhm.API_Number, swhp.API_Number, swhg.API_Number, swhap.API_Number)                                                                                                                                                                                                                                                                                                              AS API_Number
   ,coalesce(NULL, swhg.API_Number, swhm.API_Number, swhsf.API_Number, swhp.API_Number,swhwv.API_Number, swha.API_Number, swhe.API_Number)                                                                                                                                                                                                                                                                                                                                 AS API_Number
   ,coalesce(NULL, swhwv.API_State_Name, swhsf.API_State_Name, swha.API_State_Name, swhe.API_State_Name, swhm.API_State_Name, swhp.API_State_Name)                                                                                                                                                                                                                                                                                                                         AS API_State_Name
   ,coalesce(NULL, swhm.Area_Name)                                                                                                                                                                                                                                                                                                                                                                                                                                         AS Area_Name
   ,coalesce(NULL, swhwv.Big_Rig_Name, swhsf.Big_Rig_Name, swhp.Big_Rig_Name)                                                                                                                                                                                                                                                                                                                                                                                              AS Big_Rig_Name
   ,coalesce(coalesce(NULL, swhwv.Big_Rig_Spud_Date_Actual, swhp.Big_Rig_Spud_Date, swhsf.Big_Rig_Spud_Date_Actual), coalesce(NULL, swhsf.Big_Rig_Spud_Date_Planned))                                                                                                                                                                                                                                                                                                      AS Big_Rig_Spud_Date
   ,coalesce(NULL, swhwv.Big_Rig_Spud_Date_Actual, swhp.Big_Rig_Spud_Date, swhsf.Big_Rig_Spud_Date_Actual)                                                                                                                                                                                                                                                                                                                                                                 AS Big_Rig_Spud_Date_Actual
   ,coalesce(NULL, swhsf.Big_Rig_Spud_Date_Planned)                                                                                                                                                                                                                                                                                                                                                                                                                        AS Big_Rig_Spud_Date_Planned
   ,coalesce(NULL, swhp.BottomHole_Latitude_NAD27)                                                                                                                                                                                                                                                                                                                                                                                                                         AS BottomHole_Latitude_NAD27
   ,coalesce(NULL, swhp.BottomHole_Longitude_NAD27)                                                                                                                                                                                                                                                                                                                                                                                                                        AS BottomHole_Longitude_NAD27
   ,coalesce(NULL, swhg.Btu_Grid_Code)                                                                                                                                                                                                                                                                                                                                                                                                                                     AS BTU_Grid_Code  
   ,coalesce(NULL, swhwv.Completion_Date_Actual, swhp.Completion_Date_Actual)                                                                                                                                                                                                                                                                                                                                                                                              AS Completion_Date_Actual
   ,coalesce(NULL, swhwv.Conductor_Spud_Date_Actual)                                                                                                                                                                                                                                                                                                                                                                                                                       AS Conductor_Spud_Date_Actual
   ,coalesce(NULL, swhp.Configuration, swhwv.Configuration, swha.Configuration, swhm.Configuration)                                                                                                                                                                                                                                                                                                                                                                        AS Configuration
---,COALESCE(NULL, swhe.Cost_Center, swhm.Cost_Center, swhwv.Cost_Center)                                                                                                                                                                                                                                                                                                                                                                                                  AS Cost_Center
   ,coalesce(NULL, swhm.Cost_Center, swhwv.Cost_Center, swhe.Cost_Center)                                                                                                                                                                                                                                                                                                                                                                                                  AS Cost_Center
   ,coalesce(NULL, swhp.County, swhwv.County, swhsf.County, swha.County, swhe.County, swhm.County)                                                                                                                                                                                                                                                                                                                                                                         AS County
   ,coalesce(NULL, swhwv.Critical_Date_Report)                                                                                                                                                                                                                                                                                                                                                                                                                             AS Critical_Date_Report
   ,coalesce(NULL, swhwv.Current_Operations_Status)                                                                                                                                                                                                                                                                                                                                                                                                                        AS Current_Operations_Status
   ,coalesce(NULL, swhwv.Current_Operations_SubStatus)                                                                                                                                                                                                                                                                                                                                                                                                                     AS Current_Operations_SubStatus
   ,coalesce(NULL, swhm.Current_Production_Status)                                                                                                                                                                                                                                                                                                                                                                                                                         AS Current_Production_Status
   ,coalesce(NULL, sfwhfs.Design_Sand_Lbs_Per_Foot_Planned)                                                                                                                                                                                                                                                                                                                                                                                                                AS Design_Sand_Lbs_Per_Foot_Planned
   ,coalesce(NULL, sfwhfs.Design_Water_BBls_Per_Foot_Planned)                                                                                                                                                                                                                                                                                                                                                                                                              AS Design_Water_BBls_Per_Foot_Planned
   ,coalesce(NULL, swhsf.Drill_Out_End_Date_Planned)                                                                                                                                                                                                                                                                                                                                                                                                                       AS Drill_Out_End_Date_Planned
   ,coalesce(NULL, swhsf.Drill_Out_Start_Date_Planned)                                                                                                                                                                                                                                                                                                                                                                                                                     AS Drill_Out_Start_Date_Planned
   ,coalesce(NULL, sfwhwv.Completable_Lateral_Length, sfwhp.Drilled_Lateral_Length_Actual)                                                                                                                                                                                                                                                                                                                                                                                 AS Drilled_Lateral_Length_Actual
   ,coalesce(NULL, /*swhwv.Drilled_Lateral_Length_Planned,*/ sfwhsf.Drilled_Lateral_Length_Planned, sfwhp.Drilled_Lateral_Length_Planned)                                                                                                                                                                                                                                                                                                                                  AS Drilled_Lateral_Length_Planned
   ,coalesce(NULL, sfwhp.Drilled_Lateral_Length, sfwha.Cased_Lateral_Length, sfwhsf.Drilled_Lateral_Length)                                                                                                                                                                                                                                                                                                                                                                AS Drilled_Lateral_Length
   ,coalesce(NULL, sfwhwv.Completable_Lateral_Length, swhp.Completable_Lateral_Length )                                                                                                                                                                                                                                                                                                                                                                                    AS Completable_Lateral_Length
   ,coalesce(NULL, swhp.Cased_Lateral_Length)                                                                                                                                                                                                                                                                                                                                                                                                                              AS Cased_Lateral_Length
   ,coalesce(NULL, sfwhwv.Completed_Lateral_Length, sfwha.Completed_Lateral_Length)                                                                                                                                                                                                                                                                                                                                                                                        AS Completed_Lateral_Length
   ,coalesce(NULL, swhg.Planned_Lateral_Length, sfwhsf.Permitted_Lateral_Length,sfwhsf.Planned_Lateral_Length)                                                                                                                                                                                                                                                                                                                                                             AS Planned_Lateral_Length
   ,coalesce(NULL, swhwv.Drilling_Operations_Pause_Date)                                                                                                                                                                                                                                                                                                                                                                                                                   AS Drilling_Operations_Pause_Date
   ,coalesce(NULL, swhwv.Drilling_Operations_Resume_Date)                                                                                                                                                                                                                                                                                                                                                                                                                  AS Drilling_Operations_Resume_Date
   ,coalesce(NULL, swhe.Enertia_ID, swhm.Enertia_ID)                                                                                                                                                                                                                                                                                                                                                                                                                       AS Enertia_ID
   --==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--
   ,coalesce(NULL, sfwhm.First_Production_Date, sfwha.First_Production_Date_Gas_Actual, swhe.First_Production_Date,sfwhfs.First_Production_Date_Gas_Planned)                                                                                                                                                                                                                                                                                                               AS First_Production_Date
   ,coalesce(NULL, sfwhm.First_Production_Date_Gas_Actual, sfwha.First_Production_Date_Gas_Actual, swhe.First_Production_Date_Gas_Actual)                                                                                                                                                                                                                                                                                                                                  AS First_Production_Date_Gas_Actual
   ,coalesce(NULL, sfwhfs.First_Production_Date_Gas_Planned, swhsf.First_Production_Date_Gas_Planned)                                                                                                                                                                                                                                                                                                                                                                      AS First_Production_Date_Gas_Planned
   ,coalesce(NULL, sfwhm.First_Production_Date_Oil_Actual, swhe.First_Production_Date_Oil_Actual)                                                                                                                                                                                                                                                                                                                                                                          AS First_Production_Date_Oil_Actual
   --==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--
   ,coalesce(NULL, swhm.First_Sales_Date_Gas_Actual, swhwv.First_Sales_Date_Gas_Actual)                                                                                                                                                                                                                                                                                                                                                                                    AS First_Sales_Date_Gas_Actual
   ,coalesce(NULL, swhm.First_Sales_Date_Oil_Actual)                                                                                                                                                                                                                                                                                                                                                                                                                       AS First_Sales_Date_Oil_Actual
   ,coalesce(NULL, swhwv.Frac_End_Date, swhfs.Frac_End_Date)                                                                                                                                                                                                                                                                                                                                                                                                               AS Frac_End_Date
   ,coalesce(NULL, swhwv.Frac_End_Date_Actual)                                                                                                                                                                                                                                                                                                                                                                                                                             AS Frac_End_Date_Actual
   ,coalesce(NULL, swhfs.Frac_End_Date)                                                                                                                                                                                                                                                                                                                                                                                                                                    AS Frac_End_Date_Planned
   ,coalesce(NULL, swhwv.Frac_Start_Date_Actual, swhfs.Frac_Start_Date_Planned)                                                                                                                                                                                                                                                                                                                                                                                            AS Frac_Start_Date
   ,coalesce(NULL, swhwv.Frac_Start_Date_Actual)                                                                                                                                                                                                                                                                                                                                                                                                                           AS Frac_Start_Date_Actual
   ,coalesce(NULL, swhfs.Frac_Start_Date_Planned)                                                                                                                                                                                                                                                                                                                                                                                                                          AS Frac_Start_Date_Planned
   ,coalesce(NULL, sfwhp.Ground_Elevation)                                                                                                                                                                                                                                                                                                                                                                                                                                 AS Ground_Elevation
   ,coalesce(NULL, swhm.Group_Name)                                                                                                                                                                                                                                                                                                                                                                                                                                        AS Group_Name
   ,coalesce(NULL, swhsf.Longstring_Spud_Date_Planned,swha.Longstring_Spud_Date_Planned)                                                                                                                                                                                                                                                                                                                                                                                   AS Longstring_Spud_Date_Planned
   ,coalesce(NULL, swhwv.longstring_Spud_date_Actual, swha.Longstring_Spud_Date_Actual)                                                                                                                                                                                                                                                                                                                                                                                    AS Longstring_Spud_Date_Actual
   ,coalesce(NULL, sfwhe.Net_Revenue_Interest, sfwhwv.Net_Revenue_Interest, sfwha.Net_Revenue_Interest)                                                                                                                                                                                                                                                                                                                                                                    AS Net_Revenue_Interest
   ,coalesce(NULL, swhwv.Operations_Comments)                                                                                                                                                                                                                                                                                                                                                                                                                              AS Operations_Comments
   ,coalesce(NULL, swhe.Operator, swhp.Operator, swha.Operator, swhwv.Operator)                                                                                                                                                                                                                                                                                                                                                                                            AS Operator
   ,coalesce(NULL, swhe.Pad_AFE_Number)                                                                                                                                                                                                                                                                                                                                                                                                                                    AS Pad_AFE_Number
   ,coalesce(NULL, CASE WHEN coalesce(NULL,swhsf.Big_Rig_Spud_Date_Planned,swha.Longstring_Spud_Date_Planned) >= getdate() OR swhp.Symbol_Code = 'LOC' THEN swhg.Pad_Name ELSE NULL END ,CASE WHEN swhp.Symbol_Code IN ('WOBR','WOC') THEN swhwv.Pad_Name ELSE NULL END, swhm.Pad_Name)                                                                                                                                                                                    AS Pad_Name
   ,coalesce(NULL,  CASE WHEN coalesce(NULL,swhsf.Big_Rig_Spud_Date_Planned,swha.Longstring_Spud_Date_Planned) >= getdate() OR swhp.Symbol_Code = 'LOC' THEN swhg.Pad_Name_Antero_Standard ELSE NULL END ,CASE WHEN swhp.Symbol_Code IN ('WOBR','WOC') THEN swhwv.Pad_Name_Antero_Standard ELSE NULL END, swhm.Pad_Name_Antero_Standard)                                                                                                                                   AS Pad_Name_Antero_Standard
   ,coalesce(NULL, swhsf.Planned_To_Spud_In_Next_2_Years, 'No')                                                                                                                                                                                                                                                                                                                                                                                                            AS Planned_To_Spud_In_Next_2_Years
   ,coalesce(NULL, 'No')                                                                                                                                                                                                                                                                                                                                                                                                                                                   AS Planned_To_Spud_In_Next_2_Years_Default
   ,coalesce(NULL, swhsf.Planned_To_Spud_In_Next_5_Years, 'No')                                                                                                                                                                                                                                                                                                                                                                                                            AS Planned_To_Spud_In_Next_5_Years
   ,coalesce(NULL, 'No')                                                                                                                                                                                                                                                                                                                                                                                                                                                   AS Planned_To_Spud_In_Next_5_Years_Default
   ,coalesce(NULL, sfwhfs.Plug_Drillout_Days_Planned)                                                                                                                                                                                                                                                                                                                                                                                                                      AS Plug_Drillout_Days_Planned
   ,coalesce(NULL, sfwhfs.Plug_Drillout_End_Date_Planned)                                                                                                                                                                                                                                                                                                                                                                                                                  AS Plug_Drillout_End_Date_Planned
   ,coalesce(NULL, sfwhfs.Plug_Drillout_Start_Date_Planned)                                                                                                                                                                                                                                                                                                                                                                                                                AS Plug_Drillout_Start_Date_Planned
   ,coalesce(NULL, swhp.Producing_Formation, swhwv.Producing_Formation, swha.Producing_Formation)                                                                                                                                                                                                                                                                                                                                                                          AS Producing_Formation
   ,coalesce(NULL, swhm.Production_Id)                                                                                                                                                                                                                                                                                                                                                                                                                                     AS Production_Id
   ,coalesce(NULL, swha.PropNum, swhm.PropNum)                                                                                                                                                                                                                                                                                                                                                                                                                             AS PropNum
   ,coalesce(NULL, swhwv.Prospect, swhp.Prospect, swhsf.Prospect, swha.Prospect, swhfs.Prospect)                                                                                                                                                                                                                                                                                                                                                                           AS Prospect
   ,coalesce(NULL, swha.Raw_Reserve_Category)                                                                                                                                                                                                                                                                                                                                                                                                                              AS Raw_Reserve_Category
   ,coalesce(NULL, swha.Reserve_Category)                                                                                                                                                                                                                                                                                                                                                                                                                                  AS Reserve_Category
   ,coalesce(NULL, swhwv.Rig_Release_Date_Actual, swhsf.Rig_Release_Date_Actual)                                                                                                                                                                                                                                                                                                                                                                                           AS Rig_Release_Date_Actual
   ,coalesce(NULL, swhsf.Rig_Release_Date_Planned)                                                                                                                                                                                                                                                                                                                                                                                                                         AS Rig_Release_Date_Planned
   ,coalesce(NULL, swhm.Route_Name)                                                                                                                                                                                                                                                                                                                                                                                                                                        AS Route_Name
---,COALESCE(NULL, swha.SEQNUM, swhfs.SEQNUM, swhp.SEQNUM, swhsf.SEQNUM, swhg.SEQNUM,swhe.SEQNUM, swhap.SEQNUM)                                                                                                                                                                                                                                                                                                                                                            AS SEQNUM
   ,coalesce(NULL, swhg.SEQNUM,swha.SEQNUM, swhfs.SEQNUM, swhp.SEQNUM, swhsf.SEQNUM, swhe.SEQNUM, swhap.SEQNUM)                                                                                                                                                                                                                                                                                                                                                            AS SEQNUM
---,COALESCE(NULL, swhwv.Shut_In_Date, swha.Shut_In_Date, swhm.Shut_In_Date)                                                                                                                                                                                                                                                                                                                                                                                               AS Shut_In_Date
   ,coalesce(NULL, swhm.Shut_In_Date,swhwv.Shut_In_Date, swha.Shut_In_Date)                                                                                                                                                                                                                                                                                                                                                                                                AS Shut_In_Date
   ,coalesce(NULL, swhwv.Small_Rig_Name, swhsf.Small_Rig_Name)                                                                                                                                                                                                                                                                                                                                                                                                             AS Small_Rig_Name
   ,coalesce(coalesce(NULL, swhsf.Small_Rig_Spud_Date_Planned), coalesce(NULL, swhwv.Small_Rig_Spud_Date_Actual, swha.Small_Rig_Spud_Date_Actual, swhsf.Small_Rig_Spud_Date_Actual))                                                                                                                                                                                                                                                                                       AS Small_Rig_Spud_Date
   ,coalesce(NULL, swhwv.Small_Rig_Spud_Date_Actual, swha.Small_Rig_Spud_Date_Actual, swhsf.Small_Rig_Spud_Date_Actual)                                                                                                                                                                                                                                                                                                                                                    AS Small_Rig_Spud_Date_Actual
   ,coalesce(NULL, swhsf.Small_Rig_Spud_Date_Planned)                                                                                                                                                                                                                                                                                                                                                                                                                      AS Small_Rig_Spud_Date_Planned
   ,coalesce(NULL, swhp.State_Name, swhsf.State_Name, swhwv.State_Name, swha.State_Name, swhe.State_Name, swhfs.State_Name, swhm.State_Name)                                                                                                                                                                                                                                                                                                                               AS State_Name
   ,coalesce(NULL, swhp.Surface_Latitude_NAD27, swhwv.Surface_Latitude_NAD27, swha.Surface_Latitude_NAD27)                                                                                                                                                                                                                                                                                                                                                                 AS Surface_Latitude_NAD27
   ,coalesce(   NULL, swhp.Surface_Location_Shape, CASE
                                                       WHEN swhwv.Surface_Longitude_NAD27 IS NOT NULL
                                                            AND swhwv.Surface_Latitude_NAD27 IS NOT NULL THEN
                                                           geometry::STGeomFromText(concat('POINT(', swhwv.Surface_Longitude_NAD27, ' ', swhwv.Surface_Latitude_NAD27, ')'), 4267)
                                                       ELSE
                                                           NULL
                                                   END, swha.Surface_Location_Shape
            )                                                                                                                                                                                                                                                                                                                                                                                                                                                              AS Surface_Location_Shape
   ,coalesce(   NULL, swhp.Surface_Location_Shape, CASE
                                                       WHEN swhwv.Surface_Longitude_NAD27 IS NOT NULL
                                                            AND swhwv.Surface_Latitude_NAD27 IS NOT NULL THEN
                                                           geometry::STGeomFromText(concat('POINT(', swhwv.Surface_Longitude_NAD27, ' ', swhwv.Surface_Latitude_NAD27, ')'), 4267).STStartPoint()
                                                       ELSE
                                                           NULL
                                                   END, swha.Surface_Location_Shape.STStartPoint()
            )                                                                                                                                                                                                                                                                                                                                                                                                                                                              AS Surface_Location_Shape_StartPoint
   ,coalesce(NULL, swhp.Surface_Longitude_NAD27, swhwv.Surface_Longitude_NAD27, swha.Surface_Longitude_NAD27)                                                                                                                                                                                                                                                                                                                                                              AS Surface_Longitude_NAD27
   ,coalesce(NULL, swhwv.Surface_Spud_Date_Actual, swha.Surface_Spud_Date, swhsf.Surface_Spud_Date_Actual)                                                                                                                                                                                                                                                                                                                                                                 AS Surface_Spud_Date_Actual
   ,coalesce(NULL, swhsf.Surface_Spud_Date_Planned)                                                                                                                                                                                                                                                                                                                                                                                                                        AS Surface_Spud_Date_Planned
   ,coalesce(NULL, sfwhwv.Total_Measured_Depth_Actual, swhp.Total_Measured_Depth_Actual, swha.Total_Measured_Depth_Actual)                                                                                                                                                                                                                                                                                                                                                 AS Total_Measured_Depth_Actual
   ,coalesce(NULL, sfwha.Total_Vertical_Depth)                                                                                                                                                                                                                                                                                                                                                                                                                             AS Total_Vertical_Depth
   ,coalesce(NULL, swhsf.Unit_Name, swhe.Unit_Name /*, swha.Unit_Name, swhp.Unit_Name*/)                                                                                                                                                                                                                                                                                                                                                                                   AS Unit_Name
   ,coalesce(NULL, swhsf.Unit_Name_Antero_Standard, swhe.Unit_Name_Antero_Standard /*, swha.Unit_Name_Antero_Standard, swhp.Unit_Name_Antero_Standard*/)                                                                                                                                                                                                                                                                                                                   AS Unit_Name_Antero_Standard
   ,coalesce(NULL, swhe.Well_AFE_Number)                                                                                                                                                                                                                                                                                                                                                                                                                                   AS Well_AFE_Number
   --==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--
---,COALESCE(NULL, swhp.Well_Name, swha.Well_Name, swhwv.Well_Name, swhsf.Well_Name, swhm.Well_Name , swhe.Well_Name, swhfs.Well_Name, swhg.Well_Name)                                                                                                                                                                                                                                                                                                                     AS Well_Name 
   ,coalesce(NULL, swhg.Well_Name, swhfs.Well_Name, swhm.Well_Name, swhsf.Well_Name, swhp.Well_Name,swhwv.Well_Name, swha.Well_Name, swhe.Well_Name)                                                                                                                                                                                                                                                                                                                       AS Well_Name
---,COALESCE(NULL, swhp.Well_Name_Antero_Standard, swha.Well_Name_Antero_Standard, swhwv.Well_Name_Antero_Standard, swhsf.Well_Name_Antero_Standard, swhm.Well_Name_Antero_Standard, swhe.Well_Name_Antero_Standard, swhfs.Well_Name_Antero_Standard, swhg.Well_Name_Antero_Standard, swhap.Well_Name_Antero_Standard)                                                                                                                                                     AS Well_Name_Antero_Standard
   ,coalesce(NULL, swhg.Well_Name_Antero_Standard, swhfs.Well_Name_Antero_Standard, swhm.Well_Name_Antero_Standard, swhsf.Well_Name_Antero_Standard, swhp.Well_Name_Antero_Standard,swhwv.Well_Name_Antero_Standard, swha.Well_Name_Antero_Standard, swhe.Well_Name_Antero_Standard)                                                                                                                                                                                       AS Well_Name_Antero_Standard
   ,coalesce(NULL, swhsf.Pad_Name, swhp.Pad_Name, swhwv.Pad_Name, swha.Pad_Name, swhe.Pad_Name, swhm.Pad_Name)                                                                                                                                                                                                                                                                                                                                                             AS Well_Name_Pad_Header
   --   ,COALESCE(NULL, swhp.Well_Name_Title_Case, swha.Well_Name_Title_Case, swhwv.Well_Name_Title_Case, swhsf.Well_Name_Title_Case, swhm.Well_Name_Title_Case, swhe.Well_Name_Title_Case, swhfs.Well_Name_Title_Case)                                    AS Well_Name_Proper_Case
   --   ,COALESCE(NULL, swhp.Well_Name_Title_Case, swha.Well_Name_Title_Case, swhwv.Well_Name_Title_Case, swhsf.Well_Name_Title_Case, swhm.Well_Name_Title_Case, swhe.Well_Name_Title_Case, swhfs.Well_Name_Title_Case)                                    AS Well_Name_Title_Case
   ,coalesce(NULL, swhsf.Unit_Name, swhe.Unit_Name /*, swha.Unit_Name, swhp.Unit_Name*/)                                                                                                                                                                                                                                                                                                                                                                                   AS Well_Name_Unit_Header
   --==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--
   ,coalesce(NULL, swhp.Well_Number, swha.Well_Number, swhm.Well_Number)                                                                                                                                                                                                                                                                                                                                                                                                   AS Well_Number
   ,coalesce(NULL, swhp.Wellbore_Name_Antero_Standard, swha.Wellbore_Name_Antero_Standard, swhsf.Wellbore_Name_Antero_Standard, swhm.Wellbore_Name_Antero_Standard, swhe.Wellbore_Name_Antero_Standard, swhfs.Wellbore_Name_Antero_Standard,swhg.Wellbore_Name_Antero_Standard)                                                                                                                                                                                            AS Wellbore_Name_Antero_Standard
   ,coalesce(NULL, swhp.Wellbore_Name, swha.Wellbore_Name, swhsf.Wellbore_Name, swhm.Wellbore_Name, swhe.Wellbore_Name, swhfs.Wellbore_Name,swhg.Wellbore_Name)                                                                                                                                                                                                                                                                                                            AS Wellbore_Name
   ,coalesce(NULL, sfwhe.Working_Interest, sfwhwv.Working_Interest, sfwha.Working_Interest)                                                                                                                                                                                                                                                                                                                                                                                AS Working_Interest
   ,coalesce(NULL, swhp.WSN_Number, swhsf.WSN_Number)                                                                                                                                                                                                                                                                                                                                                                                                                      AS WSN_Number
   ,coalesce(NULL, sfwhwv.Casing_Set_Depth) AS Casing_Set_Depth
   ,coalesce(NULL, sfwhwv.TD_Date) AS TD_Date
   ,coalesce(NULL, sfwhwv.Max_TVD) AS Max_TVD
   ,coalesce(NULL, sfwhwv.Last_Survey_MD) AS Last_Survey_MD
   ,coalesce(NULL, sfwhwv.Last_Survey_TVD) AS Last_Survey_TVD
   ,coalesce(NULL, sfwhwv.Top_Hole_End_Date) AS Top_Hole_End_Date
   --==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--
   ,swhp.Petra_ID
   ,swha.Aries_ID
   ,swhsf.Sigmaflow_ID
   ,swhwv.WellView_ID
   ,sfwhm.Merrick_ID
   --,swha.*
   --,swhe.*
   --,swhfs.*
   ,swhfs.Completions_Group_Name
   --,swhm.*
   --,swhp.*
   --,swhsf.*
   --,swhwv.*
    -- SQL Prompt formatting off
   ,concat(
    iif(swhp.Petra_Dim_Well_Header_UID IS NOT NULL, N'P', N'_')
    , iif(swha.Aries_Dim_Well_Header_UID IS NOT NULL, N'A', N'_')
    , iif(swhsf.SigmaFlow_Dim_Well_Header_UID IS NOT NULL, N'S', N'_')
    , iif(swhwv.WellView_Dim_Well_Header_UID IS NOT NULL, N'W', N'_')
    , iif(swhm.Merrick_Dim_Well_Header_UID IS NOT NULL, N'M', N'_')
    , iif(swhe.Enertia_Dim_Well_Header_UID IS NOT NULL, N'E', N'_')
    , iif(swhfs.FracSchedule_Dim_Well_Header_UID IS NOT NULL, N'F', N'_')
    )                                                                                                                                                                                                                                                 AS Sources
-- SQL Prompt formatting on

FROM Master_Etl.Map_Well_Header             AS mwh
    LEFT JOIN Aries.Dim_Well_Header         AS swha ON mwh.Aries_Dim_Well_Header_UID = swha.Aries_Dim_Well_Header_UID
                                                       AND swha.EDW_Is_Deleted = 0
    LEFT JOIN Aries.Fact_Well_Header        AS sfwha ON swha.Aries_Dim_Well_Header_UID = sfwha.Aries_Dim_Well_Header_UID
                                                        AND sfwha.EDW_Is_Deleted = 0
    LEFT JOIN Enertia.Dim_Well_Header       AS swhe ON mwh.Enertia_Dim_Well_Header_UID = swhe.Enertia_Dim_Well_Header_UID
                                                       AND swhe.EDW_Is_Deleted = 0
    LEFT JOIN Enertia.Fact_Well_Header      AS sfwhe ON swhe.Enertia_Dim_Well_Header_UID = sfwhe.Enertia_Dim_Well_Header_UID
                                                        AND sfwhe.EDW_Is_Deleted = 0
    LEFT JOIN FracSchedule.Dim_Well_Header  AS swhfs ON mwh.FracSchedule_Dim_Well_Header_UID = swhfs.FracSchedule_Dim_Well_Header_UID
                                                        AND swhfs.EDW_Is_Deleted = 0
    LEFT JOIN FracSchedule.Fact_Well_Header AS sfwhfs ON swhfs.FracSchedule_Dim_Well_Header_UID = sfwhfs.FracSchedule_Dim_Well_Header_UID
                                                         AND sfwhfs.EDW_Is_Deleted = 0
    LEFT JOIN Merrick.Dim_Well_Header       AS swhm ON mwh.Merrick_Dim_Well_Header_UID = swhm.Merrick_Dim_Well_Header_UID
                                                       AND swhm.EDW_Is_Deleted = 0
    LEFT JOIN Merrick.Fact_Well_Header      AS sfwhm ON swhm.Merrick_ID = sfwhm.Merrick_ID
                                                        AND sfwhm.EDW_Is_Deleted = 0
    LEFT JOIN Petra.Dim_Well_Header         AS swhp ON mwh.Petra_Dim_Well_Header_UID = swhp.Petra_Dim_Well_Header_UID
                                                       AND swhp.EDW_Is_Deleted = 0
    LEFT JOIN Petra.Fact_Well_Header        AS sfwhp ON swhp.Petra_Dim_Well_Header_UID = sfwhp.Petra_Dim_Well_Header_UID
                                                        AND sfwhp.EDW_Is_Deleted = 0
    LEFT JOIN SigmaFlow.Dim_Well_Header     AS swhsf ON mwh.SigmaFlow_Dim_Well_Header_UID = swhsf.SigmaFlow_Dim_Well_Header_UID
                                                        AND swhsf.EDW_Is_Deleted = 0
    LEFT JOIN SigmaFlow.Fact_Well_Header    AS sfwhsf ON swhsf.SigmaFlow_Dim_Well_Header_UID = sfwhsf.SigmaFlow_Dim_Well_Header_UID
                                                         AND sfwhsf.EDW_Is_Deleted = 0
    LEFT JOIN WellView.Dim_Well_Header      AS swhwv ON mwh.WellView_Dim_Well_Header_UID = swhwv.WellView_Dim_Well_Header_UID
                                                        AND swhwv.EDW_Is_Deleted = 0
    LEFT JOIN WellView.Fact_Well_Header     AS sfwhwv ON swhwv.WellView_Dim_Well_Header_UID = sfwhwv.WellView_Dim_Well_Header_UID
                                                         AND sfwhwv.EDW_Is_Deleted = 0
	LEFT JOIN GIS.Dim_Well_Header			AS swhg ON mwh.GIS_Dim_Well_Header_UID = swhg.GIS_Dim_Well_Header_UID
                                                         AND swhg.EDW_Is_Deleted = 0
	LEFT JOIN Aries_Planning.Dim_Well_Header			AS swhap ON mwh.Aries_Planning_Dim_Well_Header_UID = swhap.Aries_Planning_Dim_Well_Header_UID
                                                         AND swhap.EDW_Is_Deleted = 0
	LEFT JOIN Aries_Planning.Fact_Well_Header			AS sfwhap ON mwh.Aries_Planning_Dim_Well_Header_UID = sfwhap.Aries_Planning_Dim_Well_Header_UID
                                                         AND sfwhap.EDW_Is_Deleted = 0
WHERE
    swha.Aries_Dim_Well_Header_UID IS NOT NULL
    OR sfwha.Aries_Dim_Well_Header_UID IS NOT NULL
    OR swhe.Enertia_Dim_Well_Header_UID IS NOT NULL
    OR sfwhe.Enertia_Dim_Well_Header_UID IS NOT NULL
    OR swhfs.FracSchedule_Dim_Well_Header_UID IS NOT NULL
    OR sfwhfs.FracSchedule_Dim_Well_Header_UID IS NOT NULL
    OR swhm.Merrick_Dim_Well_Header_UID IS NOT NULL
    OR sfwhm.Merrick_ID IS NOT NULL
    OR swhp.Petra_Dim_Well_Header_UID IS NOT NULL
    OR sfwhp.Petra_Dim_Well_Header_UID IS NOT NULL
    OR swhsf.SigmaFlow_Dim_Well_Header_UID IS NOT NULL
    OR sfwhsf.SigmaFlow_Dim_Well_Header_UID IS NOT NULL
    OR swhwv.WellView_Dim_Well_Header_UID IS NOT NULL
    OR sfwhwv.WellView_Dim_Well_Header_UID IS NOT NULL
	OR swhg.GIS_Dim_Well_Header_UID IS NOT NULL
	OR swhap.Aries_Planning_Dim_Well_Header_UID IS NOT NULL
	OR sfwhap.Aries_Planning_Dim_Well_Header_UID IS NOT NULL
GO

